name: "StackSpot Workflow Report Status"
description: 'StackSpot Workflow Report Status'
author: "StackSpot"
branding:
  icon: "truck"
  color: "purple"
inputs:
  execution-id:
    description: "Execution ID"
    required: true
  client-id:
    description: "Client ID StackSpot"
    required: true
  client-secret:
    description: "Client Secret StackSpot"
    required: true
  realm:
    description: "Realm StackSpot"
    required: true
  name:
    description: "Name of workflow step of status report"
    required: true
  status:
    description: "Status of execution"
    required: true
  conclusion:
    description: "Conclusion of execution"
    required: false
  idm-base-url:
    description: "StackSpot IDM base url"
    required: false
    default: "https://idm.stackspot.com"
  workflow-api-base-url:
    description: "Workflow API base url"
    required: false
    default: "https://workflow-api.v1.stackspot.com"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: 
        ${{ github.action_path }}/entrypoint.sh ${{ inputs.execution-id }} ${{ inputs.client-id }} ${{ inputs.client-secret }} ${{ inputs.realm }} "${{ inputs.name }}" ${{ inputs.status }} ${{ inputs.conclusion }} ${{ inputs.idm-base-url }} ${{ inputs.workflow-api-base-url }}
