name: Use StackSpot Workflow Report Status

on:
  workflow_dispatch:
    inputs:
      name:
        required: false
        default: Smoke test
      execution-id:
        required: true
      status:
        type: choice
        options:
          - in_progress
          - pending
          - completed
      conclusion:
        type: choice
        options:
          - success
          - failure
      log:
        required: False
        default: ""

jobs:
  stackspot-workflow:
    environment: 'prd'
    runs-on: ${{ vars.ACTION_RUNNER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stack Spot Workflow
        uses: ./
        with:
          execution-id: "${{ github.event.inputs.execution-id }}"
          name: ${{ github.event.inputs.name }}
          client-id: "${{ secrets.CLIENT_ID }}"
          client-secret: "${{ secrets.CLIENT_SECRET }}"
          realm: "${{ vars.REALM }}"
          status: "${{ github.event.inputs.status }}"
          conclusion: "${{ github.event.inputs.conclusion }}"
          log: "${{ github.event.inputs.log }}"
