name: Use StackSpot Workflow Report Status

on:
  workflow_dispatch:
    inputs:
      execution-id:
        required: true
      status:
        type: choice
        options:
          - started
          - finished

jobs:
  stackspot-workflow:
    environment: 'prd'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stack Spot Workflow
        uses: ./
        with:
          execution-id: "${{ github.event.inputs.execution-id }}"
          client-id: "${{ secrets.CLIENT_ID }}"
          client-secret: "${{ secrets.CLIENT_SECRET }}"
          realm: "${{ vars.REALM }}"
          status: "${{ github.event.inputs.status }}"